{"name": "Курьер авторизирован под некорректным паролем", "status": "skipped", "statusDetails": {"message": "XFAIL reason: [NOTRUN] yield tests were removed in pytest 4.0 - test_check_entering_invalid_password will be ignored\n\n_pytest.outcomes.XFailed: [NOTRUN] yield tests were removed in pytest 4.0 - test_check_entering_invalid_password will be ignored", "trace": "cls = <class '_pytest.runner.CallInfo'>, func = <function call_and_report.<locals>.<lambda> at 0x000001BAC60D6520>, when = 'setup', reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)\n\n    @classmethod\n    def from_call(\n        cls,\n        func: Callable[[], TResult],\n        when: Literal[\"collect\", \"setup\", \"call\", \"teardown\"],\n        reraise: type[BaseException] | tuple[type[BaseException], ...] | None = None,\n    ) -> CallInfo[TResult]:\n        \"\"\"Call func, wrapping the result in a CallInfo.\n    \n        :param func:\n            The function to call. Called without arguments.\n        :type func: Callable[[], _pytest.runner.TResult]\n        :param when:\n            The phase in which the function is called.\n        :param reraise:\n            Exception or exceptions that shall propagate if raised by the\n            function, instead of being wrapped in the CallInfo.\n        \"\"\"\n        excinfo = None\n        start = timing.time()\n        precise_start = timing.perf_counter()\n        try:\n>           result: TResult | None = func()\n\nvenv\\Lib\\site-packages\\_pytest\\runner.py:341: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nvenv\\Lib\\site-packages\\_pytest\\runner.py:242: in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\nvenv\\Lib\\site-packages\\pluggy\\_hooks.py:513: in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\nvenv\\Lib\\site-packages\\pluggy\\_manager.py:120: in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\nvenv\\Lib\\site-packages\\_pytest\\unraisableexception.py:90: in pytest_runtest_setup\n    yield from unraisable_exception_runtest_hook()\nvenv\\Lib\\site-packages\\_pytest\\unraisableexception.py:70: in unraisable_exception_runtest_hook\n    yield\nvenv\\Lib\\site-packages\\_pytest\\logging.py:840: in pytest_runtest_setup\n    yield from self._runtest_for(item, \"setup\")\nvenv\\Lib\\site-packages\\_pytest\\logging.py:829: in _runtest_for\n    yield\nvenv\\Lib\\site-packages\\_pytest\\capture.py:875: in pytest_runtest_setup\n    return (yield)\nvenv\\Lib\\site-packages\\_pytest\\threadexception.py:87: in pytest_runtest_setup\n    yield from thread_exception_runtest_hook()\nvenv\\Lib\\site-packages\\_pytest\\threadexception.py:68: in thread_exception_runtest_hook\n    yield\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nitem = <Function test_check_entering_invalid_password>\n\n    @hookimpl(tryfirst=True)\n    def pytest_runtest_setup(item: Item) -> None:\n        skipped = evaluate_skip_marks(item)\n        if skipped:\n            raise skip.Exception(skipped.reason, _use_item_location=True)\n    \n        item.stash[xfailed_key] = xfailed = evaluate_xfail_marks(item)\n        if xfailed and not item.config.option.runxfail and not xfailed.run:\n>           xfail(\"[NOTRUN] \" + xfailed.reason)\nE           _pytest.outcomes.XFailed: [NOTRUN] yield tests were removed in pytest 4.0 - test_check_entering_invalid_password will be ignored\n\nvenv\\Lib\\site-packages\\_pytest\\skipping.py:244: XFailed"}, "description": "Проверка авторизации курьера в системе, если неправильно указать пароль", "start": 1727545821805, "stop": 1727545821805, "uuid": "7a6cf816-51f6-4e01-a179-e069e3297404", "historyId": "902247381a0278474045449c0d37e85e", "testCaseId": "902247381a0278474045449c0d37e85e", "fullName": "tests.test_courier_login.TestCourierLogin#test_check_entering_invalid_password", "labels": [{"name": "feature", "value": "Courier Login Tests"}, {"name": "tag", "value": "@pytest.mark.xfail(run=False, reason='yield tests were removed in pytest 4.0 - test_check_entering_invalid_password will be ignored')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-AMN9CM3"}, {"name": "thread", "value": "15384-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}